### ISSUE TITLE
Use module::* to include deps

### ISSUE THREAD

**Issue by kpp** [Jenyay/rust-optimization#1]
https://github.com/Jenyay/rust-optimization/blob/58495c60a2a822f9d623f54569047f77d2c32ee3/examples/genetic-paraboloid/src/main.rs#L6

You can use `use optlib::genetic::*`, `use optlib::genetic::{self, *}`, or `use optlib::genetic::{self, cross, goal, logging}`. Using * won't slow down the compilation of the code

**Comment by vitvakatu** [comment]
However, using `*` imports considered bad practice by some developers, because it becomes harder to see the origin of a specific item without IDE support. Personally I prefer fully qualified imports.

**Comment by XX** [comment]
I think it is prefer to have a list of paths with a common prefix in brackets:
```rust
use optlib::genetic::{
    self, creation, cross, goal, logging, mutation, pairing, pre_birth, selection, stopchecker
};
```
