### ISSUE TITLE
No need to make examples be subprojects

### ISSUE THREAD

**Issue by kpp** [Jenyay/rust-optimization#2]
https://github.com/Jenyay/rust-optimization/blob/58495c60a2a822f9d623f54569047f77d2c32ee3/examples/genetic-paraboloid/Cargo.toml#L8

All you need is to create examples/genetic-paraboloid.rs . That's all. Take a look at: https://doc.rust-lang.org/cargo/guide/project-layout.html

**Comment by XX** [comment]
And run example with:
```bash
cargo run --example genetic-paraboloid --release
```
Examples dependencies must be added into `Cargo.toml` of main project in [`[dev-dependencies]` section](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#development-dependencies).

**Comment by Jenyay** [comment]
Thank you. It is very interesting. I did not know about the --example parameter.
